In [4]:
import numpy as np
import matplotlib.pyplot as plt
import numpy as np

from HJK.basis.monomials import monomials
#from deeptime.basis import Monomials
#import PySINDY.pysindy as ps


## Collect random datapoints from a domain

In [5]:
domain = 5
dim = 2
numIC = 1000

X = np.random.uniform(low=-domain, high=domain, size=(dim,numIC)).astype(float) 
np.shape(X)

(2, 1000)

## Monomials from `deeptime`

In [6]:
deeptime_lib = Monomials(p=2, d=2)
deeptime_lib.get_feature_names(["x1", "x2"])

['', 'x1', 'x2', 'x1^2', 'x1 x2', 'x2^2']

## Monomials from `pySINDy`

In [7]:
sindy_lib = ps.PolynomialLibrary(degree=2)

NameError: name 'ps' is not defined

## Monomials from `sklearn`

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
library = PolynomialFeatures(degree=2)

In [ ]:
#deeptime_lib.fit(X.T)
obs = deeptime_lib.transform(X.T)
np.shape(obs)

(1000, 6)

## Monomials from d3s github

In [8]:
d3s_monomials = monomials(2)
d3s_monomials.display(np.array([1.0, 1.0, 1.0, 1.0]),2)

1.000001 + 1.00000 x_1 + 1.00000 x_2 + 1.00000 x_1^2


In [14]:
X = np.array([[1, 2], [1,3]])
obs = d3s_monomials(X)
np.shape(obs)
obs

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 6.],
       [1., 9.]])

In [13]:
Dobs = d3s_monomials.diff(X)
np.shape(obs)
obs

array([[[0., 0.],
        [0., 0.]],

       [[1., 1.],
        [0., 0.]],

       [[0., 0.],
        [1., 1.]],

       [[2., 4.],
        [0., 0.]],

       [[1., 3.],
        [1., 2.]],

       [[0., 0.],
        [2., 6.]]])

In [18]:
x = obs[2:3,:]
PsiX = obs[4:,:]
np.kron(x,PsiX)

array([[ 1.,  6.,  3., 18.],
       [ 1.,  9.,  3., 27.]])